name: Checks
on:
  push:
  pull_request:
jobs:
  scalafix:
    name: Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt -v "scalafix --check" "Test / scalafix --check"
  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: ./bin/scalafmt --check
  headers:
    name: Copyright headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt -v "+ headerCheck" "+ Test / headerCheck"
